### ISSUE TITLE
Is this normal?

### ISSUE THREAD

**Issue by lemonlambda** [fufexan/webcord-flake#14]
I see this every time I use webcord and no input devices work at all
![20230109_19h32m12s_grim](https://user-images.githubusercontent.com/55360995/211435843-5d799eba-5c6c-41f3-abd1-43af6147bad6.png)

**Comment by fufexan** [comment]
Sometimes it happens. If I recall correctly, you can still change the source from something like pavucontrol.

**Comment by kuprTheMan** [comment]
I have the same problem. 
This is not normal, how fix it?

**Comment by sazurov** [comment]
the same tho

**Comment by fufexan** [comment]
I bet you're not looking for this repo. The webcord package in Nixpkgs is more up to date, while this one is stagnant. I forgot to archive, but will do it now.
