### ISSUE TITLE
Add to nixpkgs?

### ISSUE THREAD

**Issue by epetousis** [fufexan/webcord-flake#7]
Not strictly necessary, but would it be possible to get this added to nixpkgs? I found this flake through NixOS/nixpkgs#183061. Happy to adapt the flake myself if it helps.

**Comment by fufexan** [comment]
It may be possible, although I'm not sure if it's doable with dream2nix. It may need to be converted to mkYarnPackage instead.
I'm not interested in having it added to Nixpkgs personally, but feel free to add it if you want to.
