### ISSUE TITLE
Unable to install eslint alongside webcord

### ISSUE THREAD

**Issue by the-argus** [fufexan/webcord-flake#9]
My home manager path fails to build when I install ``nodePackages.eslint``, with the following logs:
```
warning: different permissions in `/nix/store/fd38ylrswrfid43qrmlm2hlw7f4bxx2y-webcord-3.8.6-wrapped/lib/node_modules/.bin/eslint' and `/nix/store/qwryxms330kfi1j9q6gi74cf7hh2ws4s-eslint-8.15.0/lib/node_modules/.bin/eslint': 0444 <-> 0555 at /nix/store/c929ggfq1n846660vxrhysla8ad1lvij-builder.pl line 103.
error: collision between `/nix/store/qwryxms330kfi1j9q6gi74cf7hh2ws4s-eslint-8.15.0/lib/node_modules/.bin/eslint' and `/nix/store/fd38ylrswrfid43qrmlm2hlw7f4bxx2y-webcord-3.8.6-wrapped/lib/node_modules/.bin/eslint'
```

I *think* this is more of a dream2nix issue, but I'm not sure. Just trying to do a web design project and I haven't done much investigation besides looking up "collision" in dream2nix issues. Nothing came up, so I'm starting here.

**Comment by fufexan** [comment]
Are you trying to install eslint in your system (or home) packages? I would rather install it in a devShell, so that they don't collide.

**Comment by the-argus** [comment]
I'm trying to install it for use in neovim for diagnostics, and I would like that functionality to always be available when I open neovim, without having to issue a nix-shell command or make a nix file and add it to git tracking.

**Comment by delet-this** [comment]
[It's a home-manager issue I think.](https://github.com/nix-community/home-manager/issues/1668) You should be able to solve it with `(hiPrio nodePackages.eslint)`

edit: I'm not sure if this specific conflict resolves with nixos `environment.systemPackages` like the clang/gcc one does though
edit2: It does, no `hiPrio` or similar required with `environment.systemPackages`
